spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6r46v9px9215i14lo.mysql.rds.aliyuncs.com:3306/bilibili_clone?useUnicode=true&characterEncoding=utf8
    username: bilibili_access
    password: Z2h2nT7TypQK#as
logging:
  level:
    root: info
  file: /opt/logs/demo.out
  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level %logger{36} [%line] - %msg%n'
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 8080