spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6r46v9px9215i14lo.mysql.rds.aliyuncs.com:3306/bilibili_clone?useUnicode=true&characterEncoding=utf8
    username: bilibili_access
    password: Z2h2nT7TypQK#as
  redis:
    # 默认数据库
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 10s
    lettuce:
      # 配置连接池
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 50
        #连接池中的最大空闲连接 默认 8
        max-idle: 8
        #连接池中的最小空闲连接 默认 0
        min-idle: 0
logging:
  level:
    root: info
  file:
    name: /opt/logs/demo.out
  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level %logger{36} [%line] - %msg%n'
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 8080