spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: blog
    password: 123456
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  minio:
    access-key: minioadmin      #key就是docker初始化是设置的，密钥相同
    secret-key: minioadmin
    url: http://localhost:9000
    bucket-name: blog-app   # 登陆minio创建的文件桶
  jackson:
    time-zone: GMT+8

mybatis-plus:
  configuration:
    # 启用 MyBatis Plus 的日志输出，以便查看 SQL 语句的生成情况
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tutorial.blog.pojo

server:
  port: 8080

logging:
  level:
    com.baomidou.mybatisplus: DEBUG
    com.tutorial.blog: DEBUG