spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6r46v9px9215i14lo.mysql.rds.aliyuncs.com:3306/bilibili_clone?useUnicode=true&characterEncoding=utf8
    username: bilibili_access
    password: Z2h2nT7TypQK#as
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 8080